# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2_api', '0002_auto_20171121_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('display_name', 'user_id')]),
        ),
    ]
